-- EN Strings
return {
	['languages'] = {
		EN = "English",
		DE = "German",
	},
	['index'] = {
		title = "Web Configuration",
		language = "Language",
	},
	['system'] = {
		title = "System Configuration",
		hostname = "Host Name",
		timezone = "Time Zone",
		locale = "Locale",
		hostname_tip = "***",
		timezone_tip = "***",
		locale_tip = "***",
		os_version = "OS Version: ",
		fedora_version = "Fedora Version: ",
	},
	['network'] = {
		title_eth  = "Ethernet Interface Configuration",
		title_wlan = "Wireless Interface Configuration",
		name  = "Name",
		type  = "Type",
		wpa_state = "Wpa State",
		dhcp = "Use DHCP",
		on_boot = "On Boot",
		add_private = "User Specified (below):",
		ipaddr = "IP Address",
		netmask= "Netmask",
		gateway= "Gateway",
		dns1   = "DNS1",
		dns2   = "DNS2",
		dns3   = "DNS3",
		domain = "Domain",
		essid  = "Network Name",
		wpa_psk = "Wireless Password",
		int_down = "Interface Down",
		int_up = "Interface Up",
		int_downup = "Interface Down / Interface Up",
		ipaddr_tip = "***",
		netmask_tip = "***",
		gateway_tip = "***",
		dns1_tip = "***",
		dns2_tip = "***",
		dns3_tip = "***",
		domain_tip = "***",
		essid_tip = "***",
		wpa_psk_tip = "***",
		on_boot_tip = "***",
		dhcp_tip = "***",
	},
	['squeezelite'] = {
		title = "Squeezelite Player Configuration and Control",
		name = "Name",
		mac  = "MAC Address",
		device = "Audio Device",
		rate = "Sample Rates",
		logfile = "Log File",
		loglevel = "Log Level",
		priority = "RT Thread Priority",
		buffer = "Buffer",
		codec = "Codec",
		alsa = "Alsa Params",
		resample = "Resample",
		dop = "DoP",
		vis = "Visulizer", 
		other = "Other Options",
		server = "Server IP Address",
		advanced = "Show Advanced Options",
		name_tip = "Set the player name",
		mac_tip = "Set mac address, format ab:cd:ef:12:34:56",
		device_tip = "Specify output device",
		rate_tip = "***",
		logfile_tip = "Write debug output to specified file",
		loglevel_tip = "Set logging level, format: &lt;log&gt;=&lt;level&gt; [&lt;log&gt;=&lt;level&gt; &lt;log&gt;=&lt;level&gt; ...], logs: all|slimproto|stream|decode|output, levels=info|debug|sdebug",
		priority_tip = "Set RT thread priority (1-99)",
		codec_tip = "Restrict codecs loaded, format: codec1, codec2, codec3",
		buffer_tip = "***",
		alsa_tip = "***",
		resample_tip = "***",
		dop_tip = "***",
		vis_tip= "***",
		other_tip = "***",
		server_tip = "***",
		advanced_tip = "***",
	},
	['squeezeserver'] = {
		title = "Squeeze Server Control",
		web_interface = "SqueezeServer Web Interface",
	},
	['storage'] = {
		title = "Storage",
		mounts = "Mounted File Systems",
		localfs = "Mount Local Disk",
		cifs = "Mount Windows Share",
		nfs = "Mount NFS Share",
		disk = "Disk",
		network = "Network",
		user = "User",
		pass = "Password",
		mountpoint = "Mountpoint",
		type = "Type",
		options = "Options",
		mount = "Mount",
		unmount = "Unmount",
		mount_perm = "Mount Permanently",
	},
	['shutdown'] = {
		title = "Shutdown: Reboot or Halt the device",
		control = "Control",
		halt = "Halt",
		halt_desc = "To halt the device, press the <b>Halt</b> button and wait at least 30 seconds before removing power for the process to complete",
		reboot = "Reboot",
		reboot_desc = "To reboot the device, press the <b>Reboot</b> button",
		force_desc = "Force (-f) reboot / halt ",
	},
	['faq'] = {
		title = "FAQ",
	},
	['help'] = {
		title = "Help",
		help = "Help",
		text = "Coming soon...",
	},
	['header'] = {
		home = "Home",
		system = "System",
		ethernet = "Ethernet Interface",
		wireless = "Wireless Interface",
		storage = "Storage",
		shutdown = "Shutdown",
		faq = "FAQ",
		help = "Help",
		squeezelite = "Squeezelite Player",
		squeezeserver = "Squeeze Server",
	},
	['footer'] = {
		copyright = "Copyright",
		version = "Version",
	},
	['base'] = { -- these are shared between all pages
		status = "Status",
		service = "Service",
		refresh = "Refresh",
		enable  = "Enable",
		disable = "Disable",
		start   = "Start",
		stop    = "Stop",
		restart = "Restart",
		enable_start = "Enable and Start",
		disable_stop = "Disable and Stop",
		reset   = "Reset",
		save    = "Save",
		save_restart = "Save and Restart",
		configuration = "Configuration",
	},
}
